import type { RangeTable, MutationEntry, TargetCurseEntry, MixCurseEntry } from './types';

export const TRACK_TYPES: RangeTable = [
  [1, 7, 'One-Shot Drums'],
  [8, 14, 'Drum Loop'],
  [15, 21, 'Percussion'],
  [22, 28, 'Bass'],
  [29, 35, 'Lead'],
  [36, 42, 'Chord'],
  [43, 49, 'Pad'],
  [50, 56, 'Piano / Keys'],
  [57, 63, 'Sample'],
  [64, 70, 'FX or Texture'],
  [71, 77, 'Arp / Sequence'],
  [78, 84, 'Vocal / Voice'],
  [85, 91, 'Acoustic Instrument'],
  [92, 98, 'Electric Instrument'],
  [99, 100, "Player's Choice"],
];

export const MUTATIONS: Record<number, MutationEntry> = {
  1: { text: 'Sum the Track to mono.' },
  3: { text: 'Track must be monophonic.' },
  5: { text: 'Limited to one octave or four slices.' },
  7: { text: 'Tracks/Slices must be fixed velocity.' },
  9: { text: 'Track must loop one bar over and over.' },
  11: { text: 'May only play on beats 1 and 3.' },
  13: { text: 'May only play on beats 2 and 4.' },
  15: { text: 'Must be played or sequenced in triplets.' },
  17: { text: 'Must not be quantized; must be played live.' },
  19: { text: 'Must be quantized to 1/16 steps.' },
  21: { text: 'Notes must be sequenced in step sequence.' },
  23: { text: "Notes/slices can't be edited once performed or programmed." },
  25: { text: 'Cannot be re-sequenced after Room resolves. Can only delete notes/slices.' },
  27: { text: 'Must be altered and resampled before processing.' },
  29: { text: 'Shorten envelope to be percussive.' },
  31: { text: 'Must use one sound or note only.' },
  33: { text: 'Cannot use the same note or slice twice.' },
  35: { text: 'Notes must be played in strict order.' },
  37: { text: 'Every note must repeat once before another may be played.' },
  39: { text: 'There can be no silence in the Track.' },
  41: { text: 'Must pass through reverb before composing.' },
  43: { text: 'Must pass through delay before composing.' },
  45: { text: 'May not use effects.' },
  47: { text: 'May use only one effect.' },
  49: { text: 'Must be side-chained to the previous Track.' },
  51: { text: 'Must be noise-gated.' },
  53: { text: 'Must pass through a low-pass filter (1 kHz).' },
  55: { text: 'Must be detuned slightly (±10 cents).' },
  57: { text: "You can't audition sounds. Pick blind before composing." },
  59: { text: 'All effects must be added and tuned before composing.' },
  61: { text: 'Mute all rhythms and the metronome for the duration of the Room.' },
  63: { text: 'Roll twice. Apply both Mutations.', mechanics: { rollTwice: true } },
  65: { text: 'Only apply effects that have already been used.' },
  67: { text: 'Must include one deliberate wrong note.' },
  69: { text: 'No Mutation.', mechanics: { noEffect: true } },
  71: { text: 'Track must abandon its intended Track Type.', mechanics: { abandonTrackType: true } },
  73: { text: 'Solo this Track for the duration of the Room.' },
  75: { text: "Only use effects that haven't been used." },
  77: { text: 'Once Room is finalized, volume is locked.' },
  79: { text: 'No Mutation.', mechanics: { noEffect: true } },
  81: { text: 'Purpose of Track changes to match previous Room. If Room One, re-roll.', mechanics: { copyPreviousTrackType: true, roomOneRule: 'reroll' } },
  83: { text: "Repeat last Room's Mutation. If first Room, no Mutation.", mechanics: { repeatLastMutation: true, roomOneRule: 'no-mutation' } },
  85: { text: 'Once you begin composing, the Room finalizes in five minutes.', mechanics: { timerMinutes: 5 } },
  87: { text: 'Must control same amount of notes as previous Track.' },
  89: { text: 'Compose Track while muted. Select sounds/patches before unmuting. Unmute ends Room.' },
  91: { text: 'Each note requires deleting one note from another Track. If Room One, no Mutation.', mechanics: { roomOneRule: 'no-mutation' } },
  93: { text: 'Take a Target Curse instead.', mechanics: { takeCurseInstead: true } },
  95: { text: "Once a note or slice is placed, it can't be moved—only deleted." },
  97: { text: 'Roll Mutations 80 or higher = delete Track. If Room One, no Mutation.', mechanics: { deleteIfHighRoll: 80, roomOneRule: 'no-mutation' } },
  99: { text: 'No Mutation.', mechanics: { noEffect: true } },
};

export const TARGET_CURSES: Record<number, TargetCurseEntry> = {
  1: { text: 'Mute until end of Run.' },
  5: { text: 'Collapse to mono.' },
  9: { text: '1/32 quantize.' },
  13: { text: 'Pan hard left or right.' },
  17: { text: 'Track must remain constant in final arrangement.' },
  21: { text: 'Resample, Chop, Reverse, Re-sequence.' },
  25: { text: 'Pitch shift one octave.' },
  29: { text: 'Apply Flanger or Chorus.' },
  33: { text: 'Force a Room. Next Room will have two Mutations.', mechanics: { forceRoom: true, doubleMutationNextRoom: true } },
  37: { text: 'Turn Track down -6 dB.' },
  41: { text: 'Strip all effects.' },
  45: { text: 'This Track is now target of all future Curses until end of Run.', mechanics: { becomesCurseTarget: true } },
  49: { text: 'Over-compress.' },
  53: { text: 'When discarding Run, roll d100. On 51+, force another Room.', mechanics: { forceRoomChance: 50 } },
  57: { text: "Delete Track. You can't replace its role.", mechanics: { deleteTrack: true } },
  61: { text: 'No re-sequencing or volume change.' },
  65: { text: 'Remove half the notes/chops.' },
  69: { text: 'Loop a short segment.' },
  73: { text: 'Erase all notes/slices except first and last.' },
  77: { text: "This Track can't loop back to back." },
  81: { text: 'Delete the first bar of the Track.' },
  85: { text: 'Delete the last bar of the Track.' },
  89: { text: 'Cannot edit Track rest of Run.' },
  93: { text: 'Apply last Curse to another Track of your choosing. If first Curse, ignore.', mechanics: { applyLastCurse: true } },
  97: { text: 'Re-roll twice.', mechanics: { rerollTwice: true } },
};

export const MIX_CURSES: Record<number, MixCurseEntry> = {
  1: { text: 'This is the last Room. If Room One or Two, re-roll.', mechanics: { isLastRoom: true, minRoom: 3 } },
  2: { text: 'Delay on Entire Mix.' },
  8: { text: 'No quantize for rest of Run. All notes performed live.' },
  15: { text: '1/32 quantize for rest of Run.' },
  22: { text: 'Decrease BPM by 10.' },
  29: { text: 'Increase BPM by 10.' },
  36: { text: 'Reverb on Entire Mix.' },
  43: { text: 'Resample Entire Mix. Disable all other Tracks.' },
  50: { text: 'Tracks can no longer resample unless instructed by Curse/Mutation.' },
  57: { text: 'Adjust your Monitoring. Cannot change for rest of Run.' },
  64: { text: 'You cannot adjust volume of previous Tracks.' },
  71: { text: 'Automation is now banned.' },
  78: { text: 'Mix must be summed to mono.' },
  85: { text: 'Only previously used effects can be used until end of Run.' },
  92: { text: 'Roll three Target Curses.', mechanics: { rollTargetCurses: 3 } },
};

export const CURSE_TARGETS_FIRST: RangeTable = [
  [1, 20, 'Previous Track'],
  [21, 40, 'Oldest Track'],
  [41, 60, 'Loudest Track'],
  [61, 80, 'Quietest Track'],
  [81, 95, "Player's Choice"],
  [96, 100, 'Roll again for two Targets'],
];

export const RUN_TAGS: [string, string][] = [
  ['Tragic', 'The Run collapsed in the last Room.'],
  ['Cursed', 'Survived 3 or more Curses.'],
  ['Compromised', 'A foundational Track was deleted or irreversibly damaged.'],
  ['Chaotic', 'You never had control of the Run.'],
  ['Unlikely', 'An unexpected Track became the foundation of the Run.'],
  ['Indebted', 'At least 2 Forced Rooms.'],
  ['Accidental', "Things worked out and you don't know why."],
  ['Clean', 'Your Run resolved with little tension.'],
  ['Unfinished', "Beat doesn't feel complete."],
  ['Adapter', 'You went with the flow.'],
  ['Cornered', 'You repeatedly worked around limitations rather than through them.'],
  ['Overextended', 'You went too far.'],
  ['Resilient', 'All hope was lost at one point.'],
  ['Hollow', 'The Run was completed… but at what cost?'],
];
