import type { RangeTable } from './types';

export const TRACK_TYPES: RangeTable = [
  [1, 7, 'One-Shot Drums'],
  [8, 14, 'Drum Loop'],
  [15, 21, 'Percussion'],
  [22, 28, 'Bass'],
  [29, 35, 'Lead'],
  [36, 42, 'Chord'],
  [43, 49, 'Pad'],
  [50, 56, 'Piano / Keys'],
  [57, 63, 'Sample'],
  [64, 70, 'FX or Texture'],
  [71, 77, 'Arp / Sequence'],
  [78, 84, 'Vocal / Voice'],
  [85, 91, 'Acoustic Instrument'],
  [92, 98, 'Electric Instrument'],
  [99, 100, "Player's Choice"],
];

export const MUTATIONS: Record<number, string> = {
  1: 'Sum the Track to mono.',
  3: 'Track must be monophonic.',
  5: 'Limited to one octave or four slices.',
  7: 'Tracks/Slices must be fixed velocity.',
  9: 'Track must loop one bar over and over.',
  11: 'May only play on beats 1 and 3.',
  13: 'May only play on beats 2 and 4.',
  15: 'Must be played or sequenced in triplets.',
  17: 'Must not be quantized; must be played live.',
  19: 'Must be quantized to 1/16 steps.',
  21: 'Notes must be sequenced in step sequence.',
  23: "Notes/slices can't be edited once performed or programmed.",
  25: 'Cannot be re-sequenced after Room resolves. Can only delete notes/slices.',
  27: 'Must be altered and resampled before processing.',
  29: 'Shorten envelope to be percussive.',
  31: 'Must use one sound or note only.',
  33: 'Cannot use the same note or slice twice.',
  35: 'Notes must be played in strict order.',
  37: 'Every note must repeat once before another may be played.',
  39: 'There can be no silence in the Track.',
  41: 'Must pass through reverb before composing.',
  43: 'Must pass through delay before composing.',
  45: 'May not use effects.',
  47: 'May use only one effect.',
  49: 'Must be side-chained to the previous Track.',
  51: 'Must be noise-gated.',
  53: 'Must pass through a low-pass filter (1 kHz).',
  55: 'Must be detuned slightly (±10 cents).',
  57: "You can't audition sounds. Pick blind before composing.",
  59: 'All effects must be added and tuned before composing.',
  61: 'Mute all rhythms and the metronome for the duration of the Room.',
  63: 'Roll twice. Apply both Mutations.',
  65: 'Only apply effects that have already been used.',
  67: 'Must include one deliberate wrong note.',
  69: 'No Mutation.',
  71: 'Track must abandon its intended Track Type.',
  73: 'Solo this Track for the duration of the Room.',
  75: "Only use effects that haven't been used.",
  77: 'Once Room is finalized, volume is locked.',
  79: 'No Mutation.',
  81: 'Purpose of Track changes to match previous Room. If Room One, re-roll.',
  83: "Repeat last Room's Mutation. If first Room, no Mutation.",
  85: 'Once you begin composing, the Room finalizes in three minutes.',
  87: 'Must control same amount of notes as previous Track.',
  89: 'Compose Track while muted. Select sounds/patches before unmuting. Unmute ends Room.',
  91: 'Each note requires deleting one note from another Track. If Room One, no Mutation.',
  93: 'Take a Target Curse instead.',
  95: "Once a note or slice is placed, it can't be moved—only deleted.",
  97: 'Roll Mutations 80 or higher = delete Track. If Room One, no Mutation.',
  99: 'No Mutation.',
};

export const TARGET_CURSES: Record<number, string> = {
  1: 'Mute until end of Run.',
  5: 'Collapse to mono.',
  9: '1/32 quantize.',
  13: 'Pan hard left or right.',
  17: 'Track must remain constant in final arrangement.',
  21: 'Resample, Chop, Reverse, Re-sequence.',
  25: 'Pitch shift one octave.',
  29: 'Apply Flanger or Chorus.',
  33: 'Force a Room. Next Room will have two Mutations.',
  37: 'Turn Track down -6 dB.',
  41: 'Strip all effects.',
  45: 'This Track is now target of all future Curses until end of Run.',
  49: 'Over-compress.',
  53: 'When discarding Run, roll d100. On 51+, force another Room.',
  57: "Delete Track. You can't replace its role.",
  61: 'No re-sequencing or volume change.',
  65: 'Remove half the notes/chops.',
  69: 'Loop a short segment.',
  73: 'Erase all notes/slices except first and last.',
  77: "This Track can't loop back to back.",
  81: 'Delete the first bar of the Track.',
  85: 'Delete the last bar of the Track.',
  89: 'Cannot edit Track rest of Run.',
  93: 'Apply last Curse to another Track of your choosing. If first Curse, ignore.',
  97: 'Re-roll twice.',
};

export const MIX_CURSES: Record<number, string> = {
  1: 'This is the last Room. If Room One or Two, re-roll.',
  2: 'Delay on Entire Mix.',
  8: 'No quantize for rest of Run. All notes performed live.',
  15: '1/32 quantize for rest of Run.',
  22: 'Decrease BPM by 10.',
  29: 'Increase BPM by 10.',
  36: 'Reverb on Entire Mix.',
  43: 'Resample Entire Mix. Disable all other Tracks.',
  50: 'Tracks can no longer resample unless instructed by Curse/Mutation.',
  57: 'Adjust your Monitoring. Cannot change for rest of Run.',
  64: 'You cannot adjust volume of previous Tracks.',
  71: 'Automation is now banned.',
  78: 'Mix must be summed to mono.',
  85: 'Only previously used effects can be used until end of Run.',
  92: 'Roll three Target Curses.',
};

export const CURSE_TARGETS_FIRST: RangeTable = [
  [1, 20, 'Previous Track'],
  [21, 40, 'Oldest Track'],
  [41, 60, 'Loudest Track'],
  [61, 80, 'Quietest Track'],
  [81, 95, "Player's Choice"],
  [96, 100, 'Roll again for two Targets'],
];

export const RUN_TAGS: [string, string][] = [
  ['Tragic', 'The Run collapsed in the last Room.'],
  ['Cursed', 'Survived 3 or more Curses.'],
  ['Compromised', 'A foundational Track was deleted or irreversibly damaged.'],
  ['Chaotic', 'You never had control of the Run.'],
  ['Unlikely', 'An unexpected Track became the foundation of the Run.'],
  ['Indebted', 'At least 2 Forced Rooms.'],
  ['Accidental', "Things worked out and you don't know why."],
  ['Clean', 'Your Run resolved with little tension.'],
  ['Unfinished', "Beat doesn't feel complete."],
  ['Adapter', 'You went with the flow.'],
  ['Cornered', 'You repeatedly worked around limitations rather than through them.'],
  ['Overextended', 'You went too far.'],
  ['Resilient', 'All hope was lost at one point.'],
  ['Hollow', 'The Run was completed… but at what cost?'],
];
